### ISSUE TITLE
NPE while getting UUID from checkpoint

### ISSUE THREAD

**Issue by zzvara** [couchbase/couchbase-elasticsearch-connector#143]
This NPE is thrown each time when I'd like to register the CAPI as an XCDR cluster. Cluster is registered in Couchbase, but an `Invalid response error` is returned. Something is really messing around. All I did before that is to delete the cluster reference, and tried to recreate it. in Couchbase UI.

[2016-12-06 20:17:08,039][WARN ][org.eclipse.jetty.servlet.ServletHandler] /pools/default/buckets
java.lang.NullPointerException
        at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.getUUIDFromCheckpointDocSource(ElasticSearchCouchbaseBehavior.java:134)
        at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.lookupUUID(ElasticSearchCouchbaseBehavior.java:155)
        at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.getBucketUUID(ElasticSearchCouchbaseBehavior.java:205)
        at com.couchbase.capi.servlet.BucketMapServlet.formatBuckets(BucketMapServlet.java:121)
        at com.couchbase.capi.servlet.BucketMapServlet.executeBucketsRequest(BucketMapServlet.java:109)
        at com.couchbase.capi.servlet.BucketMapServlet.doGet(BucketMapServlet.java:79)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:542)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

Version: `2.5.0-alpha4`.

**Comment by zzvara** [comment]
Reinstalled and reconfigured ES solved it, but lost all the indices and data.

**Comment by zzvara** [comment]
This bug is still a huge hit on CB 4.5.0 and ES 5.3.0 with corresponding plugin.

**Comment by dnault** [comment]
Recommending upgrading to version 4 of the connector, which no longer uses the CAPI protocol.
