### ISSUE TITLE
CB XDCR pauses and Jetty errors - connection reset by peer

### ISSUE THREAD

**Issue by lexicalparadox** [couchbase/couchbase-elasticsearch-connector#192]
Hi there,

We're using Couchbase Enterprise Edition, version 5.1.1 Build 5723 and ES, version 5.7.6.
The plugin version we're using is: elasticsearch-transport-couchbase-3.0.1-cypress-es5.6.7

We were doing load tests today and noticed that the XDCR between CB and ES was not making progress. We saw this in the CB admin console. Typically we would see the percentage completion to be at 100%. But under load, we noticed that it would pause at 95%. I tried re-setting up the XDCR between CB and ES by dropping the linkage and re-creating it, but this time we're seeing that XDCR continually hovers around 65% and continually regresses back to 50% or so and never makes progress past 70%. I took look at our logs on the ES cluster  and noticed several errors related to Jetty in the logs. As I understand it, the plugin uses jetty servlets to expose a REST API so that CB can sync with the ES Node using the plugin. 

In regards to deployment/architecture for our cluster, please keep in mind that we do have a 2 DC, active-active setup for CB. So, we do have an XDCR linkage between DC1 and DC2 for just CB alone, and additionally, we also have a corresponding ES cluster for DC1 and DC2, each. We have also set up the XDCR linkage between CB DC1 to ES DC1 and and CB DC2 to ES DC2. We've noticed that DC1 works just fine, but DC2 is having issues. The hardware is similar and the configurations for CB and ES are the same. Any idea would be super helpful! Thanks much.

We're seeing various errors such as the following:

1.
```
[2018-09-05T03:27:09,596][DEBUG][o.e.j.i.WriteFlusher     ] write exception
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:199) ~[jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:420) ~[jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:738) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:518) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:724) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:775) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:219) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:496) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.codehaus.jackson.impl.Utf8Generator._flushBuffer(Utf8Generator.java:1754) [jackson-core-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.impl.Utf8Generator.close(Utf8Generator.java:1119) [jackson-core-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ObjectMapper._configAndWriteValue(ObjectMapper.java:2577) [jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ObjectMapper.writeValue(ObjectMapper.java:2065) [jackson-mapper-asl-1.9.8.jar:1.9.8]
	at com.couchbase.capi.servlet.CAPIServlet.handleRevsDiff(CAPIServlet.java:347) [couchbase-capi-server-1.6.3.jar:?]
	at com.couchbase.capi.servlet.CAPIServlet.service(CAPIServlet.java:91) [couchbase-capi-server-1.6.3.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513) [jetty-security-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.Server.handle(Server.java:523) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:?]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:179) ~[?:?]
	... 42 more
```

2. 
```
[2018-09-05T01:32:58,383][WARN ][o.e.j.h.HttpParser       ] Illegal character 0x16 in state=START for buffer HeapByteBuffer@3e0a63ae[p=1,l=247,c=8192,r=246]={\x16<<<\x03\x01\x00\xF2\x01\x00\x00\xEe\x03\x03[\x8f2J\xF1%\xDf...\x03\x02\x03\x03\x02\x01\x02\x02\x02\x03\x00\x0f\x00\x01\x01>>>\n\r\n{"bucket":"prs...mh0dHBzOi8vc3Rv}
```

3.
```
[2018-09-05T01:32:58,383][WARN ][o.e.j.h.HttpParser       ] bad HTTP parsed: 400 Illegal character 0x16 for HttpChannelOverHttp@1607381b{r=0,c=false,a=IDLE,uri=null}
org.eclipse.jetty.http.HttpParser$IllegalCharacterException: 400: Illegal character 0x16
	at org.eclipse.jetty.http.HttpParser.next(HttpParser.java:481) ~[jetty-http-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.http.HttpParser.quickStart(HttpParser.java:544) ~[jetty-http-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1306) [jetty-http-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:350) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

4.
```
[2018-09-05T01:45:51,140][DEBUG][o.e.j.s.HttpChannel      ] Could not send response error 500, already committed
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:199) ~[jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:420) ~[jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313) ~[jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140) ~[jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:738) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:518) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:724) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:775) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:219) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:496) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.codehaus.jackson.impl.Utf8Generator._flushBuffer(Utf8Generator.java:1754) ~[jackson-core-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.impl.Utf8Generator._writeFieldName(Utf8Generator.java:420) ~[jackson-core-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.impl.Utf8Generator.writeFieldName(Utf8Generator.java:282) ~[jackson-core-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ser.std.StdKeySerializer.serialize(StdKeySerializer.java:33) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ser.std.MapSerializer.serializeFields(MapSerializer.java:243) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:186) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:23) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:610) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ObjectMapper._configAndWriteValue(ObjectMapper.java:2575) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at org.codehaus.jackson.map.ObjectMapper.writeValue(ObjectMapper.java:2065) ~[jackson-mapper-asl-1.9.8.jar:1.9.8]
	at com.couchbase.capi.servlet.CAPIServlet.handleRevsDiff(CAPIServlet.java:347) ~[couchbase-capi-server-1.6.3.jar:?]
	at com.couchbase.capi.servlet.CAPIServlet.service(CAPIServlet.java:91) ~[couchbase-capi-server-1.6.3.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) ~[jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513) ~[jetty-security-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.Server.handle(Server.java:523) ~[jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:?]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:179) ~[?:?]
	... 49 more
```

**Comment by dnault** [comment]
Regarding "Illegal character 0x16", is there any chance some client is attempting to talk to the plugin using HTTPS?

https://bugs.eclipse.org/bugs/show_bug.cgi?id=471081
https://github.com/cryptomator/cryptomator/issues/410

**Comment by lexicalparadox** [comment]
Thanks, David. It's possible that a client may have tried over HTTPs, but I'm not too concerned on that, if that's the case.

So it looks like this issue is consistently reproducible under load. I tried to delete the XDCR link and re-create it. I've noticed these in the logs:

```
[2018-09-06T17:20:13,202][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] enter revsDiff requestId=3178429 database=prod/599
[2018-09-06T17:20:13,202][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] enter revsDiff requestId=3178432 database=prod/649
[2018-09-06T17:20:13,203][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] enter revsDiff requestId=3178435 database=prod/1014
[2018-09-06T17:20:13,202][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] exit revsDiff requestId=3178421 database=prod/414 elapsedMs=0
[2018-09-06T17:20:13,203][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] exit revsDiff requestId=3178430 database=prod/559 elapsedMs=0
[2018-09-06T17:20:13,203][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] enter revsDiff requestId=3178434 database=prod/674
[2018-09-06T17:20:13,202][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] no uuid in database name
[2018-09-06T17:20:13,202][DEBUG][org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl] [master-05] no uuid in database name
```

Can you tell me what "no uuid in database name" means? And if this should be concerning? This did come as a DEBUG log.

**Comment by dnault** [comment]
> I am a little bit confused here - on the CB cluster side, if each node has 1024 vBuckets + 2048 replica vBuckets for a total of 3072 vBuckets, what should we set this couchbase.num_vbuckets parameter to? 1024? Or 3072? 

`1024`.

> Also, if we have a 5 node CB cluster, and each CB node has 1024 vBuckets + 2048 vBuckets, do we need to set couchbase.num_vbuckets to 1024 * 5 = 5120 or 3072 * 5 = 15360?

`1024`. This value is independent of cluster size or number of replicas. Just ask, "Is the Couchbase cluster I'm replicating *from* running on macOS?" If so, the correct value is `64`. Otherwise the correct value is `1024`. 

> What happens when more vBuckets are created on the CB cluster side when new keys are created?

Every Couchbase bucket is partitioned into `64` or `1024` vbuckets, depending on the host OS. New vbuckets aren't created, or dynamically allocated, or anything like that. They're just a way to partition the dataset so Couchbase can do its high availability magic.

Elasticsearch doesn't care about vbuckets, but the plug-in has to *pretend to care* since it's *pretending* to be a Couchbase node. In order participate in XDCR with the other Couchbase nodes, it has to advertise the same number of vbuckets as the real nodes in the cluster.

**Comment by dnault** [comment]
> Can you tell me what "no uuid in database name" means? And if this should be concerning? This did come as a DEBUG log.

This seems to be an expected condition that is handled gracefully by just ignoring the UUID component of the database name, but I'm not certain. Would need to investigate more. Do you still see it if you delete the ES index before recreating the XDCR link?

The quickest path to success might be to try version 4 of the connector, which was just released. It uses a modern replication protocol that is less prone to the kinds of issues you're seeing with CAPI.

https://docs.couchbase.com/elasticsearch-connector/4.0/getting-started.html

**Comment by dnault** [comment]
Hi Lex,
Should we continue tracking this issue, or do you think you'll be using version 4.0 of the connector?
Thanks,
David
