### ISSUE TITLE
XDCR creation fails when there is an alias on multiple indexes

### ISSUE THREAD

**Issue by arthurgimpel** [couchbase/couchbase-elasticsearch-connector#77]
When creating a XDCR to Elasticsearch cluster which has an alias for more than one index (same alias) the operation fails. 
I attempted to create the XDCR connection to an index which is not related to that alias, but it still failed.

Error from couchbase:

ERROR: Got HTTP status 500 from REST call get to http://10.211.55.18:9091/pools/default/buckets?uuid=f4268e62702130298bf87f17cc481219&forXDCR=1. Body was: "<html>\n<head>\n<meta http-equiv=\"Content-Type\" co"

Error logged in Elasticsearch's log file:

[2015-03-24 09:20:59,362][WARN ][org.eclipse.jetty.servlet.ServletHandler] /pools/default/buckets
org.elasticsearch.ElasticsearchIllegalArgumentException: Alias [proxy_logs] has more than one index associated with it [[proxy_logs-2015.3.8, proxy_logs-2015.3.9]], can't execute a single index op
    at org.elasticsearch.cluster.metadata.MetaData.resolveIndexRouting(MetaData.java:460)
    at org.elasticsearch.action.get.TransportGetAction.resolveRequest(TransportGetAction.java:86)
    at org.elasticsearch.action.get.TransportGetAction.resolveRequest(TransportGetAction.java:43)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.<init>(TransportShardSingleOperationAction.java:114)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.<init>(TransportShardSingleOperationAction.java:93)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:72)
    at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:49)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:65)
    at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:92)
    at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:189)
    at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:196)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
    at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.lookupUUID(ElasticSearchCouchbaseBehavior.java:129)
    at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.getBucketUUID(ElasticSearchCouchbaseBehavior.java:178)
    at com.couchbase.capi.servlet.BucketMapServlet.formatBuckets(BucketMapServlet.java:121)
    at com.couchbase.capi.servlet.BucketMapServlet.executeBucketsRequest(BucketMapServlet.java:109)
    at com.couchbase.capi.servlet.BucketMapServlet.doGet(BucketMapServlet.java:79)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:485)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:916)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:634)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Thread.java:745)

**Comment by rajeshetty** [comment]
I have the same problem. Plugin should be able to resolve this and send the updates to respective indexes.

**Comment by dnault** [comment]
Elasticsearch does not support writing to aliases that refer to multiple indexes. This post on the Elastic forum suggests a workaround:

https://discuss.elastic.co/t/one-alias-with-multiple-indices/22230/2?u=dnault
